site_name: The O.A.S.I.S. Project
site_url: https://www.oasisproject.net/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    - scheme: ironman
    #  toggle:
    #    icon: material/brightness-7
    #    name: Switch to dark mode

    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    #- scheme: ironman-dark
    #  toggle:
    #    icon: material/brightness-4
    #    name: Switch to system preference

nav:
  - Home: index.md
  - Overview: overview.md
  - Videos: videos.md
  - M.I.R.A.G.E.: mirage.md
  - D.A.W.N.: dawn.md
  - A.U.R.A.: aura.md
  - S.P.A.R.K.: spark.md
  - Communications: comms.md
  - B.E.A.C.O.N. Parts Catalog: beacon.md
  - Open Source and Special Thanks: opensource.md
  - Credits: credits.md
  #- Blog: blog/index.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - social
  - blog
  - mkdocs-video:
      css_style:
        display: block
        width: 720px
        height: 405px
        margin-left: auto
        margin-right: auto
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/kerseyfabs
    - icon: fontawesome/brands/github-alt
      link: https://github.com/The-OASIS-Project
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KerseyFabs
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/KerseyFabrications

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/The-OASIS-Project/

copyright: |
  &copy; 2024 <a href="https://github.com/KerseyFabrications"  target="_blank" rel="noopener">Kersey Fabrications</a>