site_name: The O.A.S.I.S. Project
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  #palette:
    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    #- scheme: ironman
    #  toggle:
    #    icon: material/brightness-7
    #    name: Switch to dark mode

    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: ironman-dark
    #  toggle:
    #    icon: material/brightness-4
    #    name: Switch to system preference

#extra_css:
#  - stylesheets/extra.css

plugins:
  - search
  - social
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/The-OASIS-Project
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KerseyFabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/KerseyFabrications"  target="_blank" rel="noopener">Kersey Fabrications</a>